### ISSUE TITLE
Provide the line in the current test function

### ISSUE THREAD

**Issue by blueyed** [fschulze/pytest-pdb#1]
Currently it will print:

> Currently in foo/test_foo.py:3119: test_foo

But looking at `bt` it shows:

> [47]   foo/test_foo.py(3133)test_foo()

While the location of the test function (line 3119) is good to know in general, I am more interested in where I am in the current test.
I think this information should be with the "Currently in" for easy copy'n'paste:

> Currently in foo/test_foo.py:3133: test_foo

Not sure if the line where the test is defined is important enough to have it there also, but then it should come afterwards:

> Currently in foo/test_foo.py:3133: test_foo (defined in line 3119)

**Comment by fschulze** [comment]
Thanks for the suggestion.

It's been a while since I wrote this. I'm not sure the information is available. I'll take a look when I get the chance.
